dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: java
jdk:
- oraclejdk8

notifications:
  slack: arquisofti2b:5f14wMgpnF6luTNIoBZopzFq#travis
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - mysql

before_script:
  - export DB_URL=localhost
  - export DB_USER=root
  - export DB_PASSWORD=root
  - export VOTING_DB_URL=localhost
  - export VOTING_DB_USER=root
  - export VOTING_DB_PASSWORD=root
  - sh -c "mysqladmin -u root password root"
  - sh -c "mysql -u root -proot -e 'create database IF NOT EXISTS voters;'"
  - sh -c "mysql -u root -proot -e 'create database IF NOT EXISTS results;'"


script:
  - sh test.sh