version: '2'
services:
  db:
    container_name: "db"
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=rootsecret
       - MYSQL_DATABASE=voters
       - MYSQL_USER=asw
       - MYSQL_PASSWORD=secret

  censuses:
    container_name: "censuses"
    image: emibloque/censusesi2
    depends_on:
      - db
    environment:
      - DB_URL=db
      - DB_USER=asw
      - DB_PASSWORD=secret

  voter-access:
    container_name: "voter-access"
    image: emibloque/votersi2
    ports:
      - "8443:8443"
    depends_on:
      - db
    environment:
      - DB_URL=db
      - DB_USER=asw
      - DB_PASSWORD=secret

  web-app:
    image: emibloque/votersi2-web
    ports:
      - "8888:8888"
    depends_on:
      - voter-access
    environment:
      - API_URL=voter-access:8443



  voting-db:
    container_name: "voting-db"
    image: mysql:5.6
    environment:
       - MYSQL_ROOT_PASSWORD=rootsecret
       - MYSQL_DATABASE=voting
       - MYSQL_USER=asw
       - MYSQL_PASSWORD=secret

  votingsystem:
    container_name: "votingsystem"
    image: emibloque/votingsystem
    ports:
      - "8200:8200"
    depends_on:
      - voting-db
    environment:
      - VOTING_DB_URL=voting-db
      - VOTING_DB_USER=asw
      - VOTING_DB_PASSWORD=secret

  results:
    container_name: "results"
    image: emibloque/votecountingi2-results
    ports:
      - "8080:8080"
    depends_on:
      - voting-db
    environment:
      - VOTING_DB_URL=voting-db
      - VOTING_DB_USER=asw
      - VOTING_DB_PASSWORD=secret

  counting:
    container_name: "counting"
    image: emibloque/votecountingi2-counting
    depends_on:
      - voting-db
    environment:
      - VOTING_DB_URL=voting-db
      - VOTING_DB_USER=asw
      - VOTING_DB_PASSWORD=secret